@host = http://localhost:4400

###

GET {{host}}/api/hello

### 

POST {{host}}/api/beverages/tea?sugar=yes&milk=yes
Content-Type: application/json
codecool-beverages-dietary: lactose-intolerance

{
    "kind":"Englist-breakfast"
}